
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AnimatedBackground from "@/components/animata/background/animated-background";
import "./globals.css"
import "@/amplify/configure";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" absolute ">
          <AnimatedBackground />
        </div>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
