import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"
import "./app.css"
import AnimatedBackground from "@/components/animata/background/animated-background";
import AuthenticatorWrapper from "./authenticator-wrapper";
import "@aws-amplify/ui-react/styles.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

      <html lang="en">
      <body >

      <main >
          <AuthenticatorWrapper>{children}</AuthenticatorWrapper>
      </main>
      </body>

      </html>
  );
}
